services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecret53412@$
      POSTGRES_DB: 10Backend

  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    environment:
      # Required by pgAdmin
      PGADMIN_DEFAULT_EMAIL: jefeing.esteban@gmail.com
      PGADMIN_DEFAULT_PASSWORD: MySecret53412@$

      # Don't require the user to login
      PGADMIN_CONFIG_SERVER_MODE: 'False'

      # Dont require a "master" password after logging in
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'