version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: postgres-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecret53412@$
      POSTGRES_DB: 10Backend
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: pgadmin-1
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jefeing.esteban@gmail.com
      PGADMIN_DEFAULT_PASSWORD: MySecret53412@$
      # Desktop mode configuration
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    networks:
      - backend-network
    depends_on:
      - postgres

  backend:
    image: ubuntu
    container_name: 10B-Backend
    # This command keeps the empty Ubuntu container running
    command: tail -f /dev/null 
    ports:
      - "6000:5050"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge